---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pharmacy-qa-secret
  namespace: pharmacy-qa
spec:
  encryptedData:
    OPENAI_API_KEY: AgAxogD2Vn6SfPZDJpNW3me6zGKW2wGaCI0hWNP5c6W+hhr2qdrVCDF4DTue0CuvhDcwRMdDspnhqf7tKoKxYZzZFw+dYxafZ/HBWRK757vibT1YWnhZHwMTIUxm4Xi9Q/2jeAZCamWcyBLFUKhEuax+gaNxunOuBPqzFESQ2rT2u/GtMmD7/tH4oi5meXaj00O00i4A7tuR0qJHBwlLU4bOiEy5oGjp7ViQn6uEpX2tNTvjlyvDdx7n8c5fzxDjrrE+MqR5RDlv3ToAvEXALOsqJkzRVoFMRH/qc0g1GLIyz+HB/8HH/ie/8q2enFxDO3FB5f/RU1arV4SPUZ7+JC+I5MtkV0RpitR6lHJKAs1AYNTaHE6aUgO36K7ca82gSaebv5Uspa3Cv4an6oK7IjEfIn06wNFxGMPb/B6Eu+Jx+Q2BKtHtwrAc3moWGbwUpENADuEai7Ic0fg7l3oGoYANniM4Tb7c08QTs3vdnPhAJw0srQXA+pDh5cNKQgg4Q2ubWYgN0yiH0UILx2/P1dmX4+xxnVJkuguFCWZX3Go5JlWjAKMz7ESgwWpKzh+S0cu2pktqRZyzmxBB/8nrDHWTITwK08OeQp3zIwhtowF6fFixhJ7YkRd9muWpgekwyQ2Dt0oh4mH3bcjaBRZqQVovckiR1yNqQJfccSLtAWvwPSBMzmBqidMBmqPYM6gmAu4BAYc8kf6GzczLZ+M+92eFHhissNMethN5J+jTlD6jlR1zMtC40i3bFebQsDE6kV8bkPYu55BF8K2unrWHVXtTqRVZ1dvgD5oHQp8rHEzrJ/6c0OQvcIGZL2mv9nOUPXpnGG19Ftzso5DEyMl6RAtG8rNg0AgSJmgRLKUjOm8QdOBVP0bAJqTigrHS2q1072KozL6+iZ9qk+Gx/MBY7HSXz3wdeA==
  template:
    metadata:
      name: pharmacy-qa-secret
      namespace: pharmacy-qa
