---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pharmacy-qa-secret
  namespace: pharmacy-qa
spec:
  encryptedData:
    OPENAI_API_KEY: AgB9Yp4HWLWdvYUnlS3HNBzqPEBtcCC6xP557gGS48ZXf+soqbtDrmSBbflQ/WAHOEqsOIfZ8qxF9J/ii5oNTShY99Cs20zUsXs0PGWE++jWZ+H7fHUfBZXRn+YpRNHeFFODgP3NL8rBh02cri3IlP4jTd68CWbYeyyGtRErIz3IEcI/uMX555AxwHw4N/i80oj61XP13D9wdQZwP1MbW6jokQAd99OLOE6O7iK/NOQ2VyzYIAgKhMXMnN0oQhNj/DJfoNLcVg40ouovZj/qU/3NvkzY5n8i8OCom5+rHjfgtrHPV2po3us7eZm1Md09u2cGB/d9xi8fyvZax/+UsHyT3WGp6ubShHfD3MIYKfLTssYWX08Af3oo9uobuzPC7T2xOcDT2N3qxG8qej4C/I1nttey+4HuEIu/Cc7Crh4cIdB0RArEIiROkisIYQg/jYYItxxbe6VxpQGuR923UkoNYUFQCHEOPcdv5strAhqxnjgxXvwNTOBLsGZaR2WNjy8xAsUSjXpGGmFostNunsrtG77qJRN8HDQ7GJUwqdAvCt4GwvtO4axhg12KhKeSHr1vnSBc4iifWCWS/6tr0JSEWrCxR/A/RJJF7nkJ2EJ4TQN+WX5IeBwQpSeQHTjDXeplF/JoBORxxgM7iInD3U8+P9MTUMSxHEmBDeuk6UqDTM0TGOUZ22C1qTt3fbrgnSh90hNr0HxcVnzoHpyIhIEspqjdZNT3hS97h3/mk7dEN4PjqVNDGUPnqloSlnL7g1pAyRkSt1/hsfAAoRjYUNVj4hRwuL3JOYWFkzKcpoeqim5lYyocMaEQC/2Zdl7vmQKlYUsxEX4sdvCo6hFvObwm0wNopxABoVL9Ta8o783hrr1ltUKPuuk0vQqTJZrIsAeRwJFC7UgWM9EPo55A73ORJugcfA==
  template:
    metadata:
      name: pharmacy-qa-secret
      namespace: pharmacy-qa
